const config = {
  BASE_URL: import.meta.env.VITE_BASE_URL,
  ENDPOINTS: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    EMAIL_CHECK: "/auth/email-check",
    INTENT: "/payment/sepa-payment-intent",
    TENANT: "/tenant",
    // Password reset endpoints
    FORGOT_PASSWORD: "/auth/request-reset-password-otp",
    VERIFY_OTP: "/auth/verify-reset-password-otp",
    RESET_PASSWORD: "/auth/set-new-password",
    ME: "/auth/me",
    THEMES: "/webshop/themes",
    PAGES:"/webshop/pages",
    UPDATE_PASSWORD: "/auth/update-password",
    VERIFY_SIGNUP: "/auth/verify-signup",
    RESEND_VERIFICATION: "/auth/resend-password-reset-otp",
    // Email verification endpoints
    VERIFY_EMAIL_LINK: "/auth/verify-email-link",
    RESEND_EMAIL_VERIFICATION: "/auth/resend-email-verification",
    REFRESH: "/refresh-token",
    SETUP: "/tenant/setup",
    LOCATIONS: "/locations",
    GET_LOCATION: "/locations/:id",
    UPDATE_LOCATION: "/locations/:id",
    EMPLOYEES: "/employees",
    UPDATE_EMPLOYEE: "/employees/:id",
    UPDATE_RECEIPT: "/locations/:id/rcp",
    // Product management endpoints
    PRODUCTS: "/products",
    ORDERS: "/orders",
    PRODUCT_BY_ID: "/products/:id",
    VARIANTS: "/products/:productId/variants",
    VARIANT_BY_ID: "/products/:productId/variants/:id",
    INVENTORY: "/inventory",
    INVENTORY_BY_LOCATION: "/inventory/location/:locationId",
    // Category management endpoints
    CATEGORIES: "/categories",
    CATEGORY_BY_ID: "/categories/:id",
    // Media/File upload endpoints
    MEDIA_S3_UPLOAD_URL: "/media/s3/upload-url",
    MEDIA_S3_CLEANUP: "/media/s3/mark-cleanup",
    MEDIA_S3_CONFIRM: "/media/s3/confirm-usage",
    MEDIA_S3_DELETE: "/media/s3/delete",
    MEDIA_S3_BULK_DELETE: "/media/s3/bulk-delete",
    // Stripe Connect endpoints
    STRIPE_CREATE_ACCOUNT: "/merchants/create-account",
    STRIPE_GET_ACCOUNT: "/merchants/:accountId",
    STRIPE_CREATE_LOCATION: "/merchants/location",
    STRIPE_ACCOUNT_SESSION: "/merchants/account-session",
    STRIPE_ACCOUNT_STATUS: "/merchants/:accountId/status",
    STRIPE_GET_READERS: "/terminals/readers/:stripeAccountID/:location",
    STRIPE_LOGIN_LINK: "/merchants/login-link",
    STRIPE_REGISTER_READER: "/terminals/register-reader",
    PROFILE_UPDATE: "/auth/update-profile",
    UPDATE_STATUS: "/auth/update-setup-status",
    CHANGE_PASSWORD: "/auth/change-password",
    GET_REVENUE: "/orders/revenue",
    GET_ORDER_COUNT: "/orders/sales-count",
    // Analytics endpoints
    ORDER_STATISTICS: "/orders/get-order-statistics",
    REVENUE_STATISTICS: "/orders/get-revenue-statistics",
    LOCATION_ANALYTICS: "/orders/stats",
  },
};

export default config;
